return {
  "nvim-treesitter/nvim-treesitter",
  dependencies = {
    "nvim-treesitter/nvim-treesitter-textobjects",
  },
  build = ":TSUpdate",
 event = "VeryLazy",
  main = "nvim-treesitter.configs",
  opts = {
    ensure_installed = {
      "angular",
      "c_sharp",
      "css",
      "csv",
      "editorconfig",
      "git_config",
      "gitignore",
      "html",
      "http",
      "ini",
      "javascript",
      "jsdoc",
      "lua",
      "luap",
      "luadoc",
      "markdown",
      "markdown_inline",
      "php",
      "php_only",
      "phpdoc",
      "regex",
      "sql",
      "twig",
      "typescript",
      "vim",
      "vimdoc",
      "vue",
      "xml",
      "yaml",
    },
    highlight = {enable = true},
    indent = {enable = true},
    textobjects = {
      select = {
        enable = true,
        lookahead = true,
        keymaps = {
          ["af"] = "@function.outer",
          ["if"] = "@function.inner",
          ["ac"] = "@conditional.outer",
          ["ic"] = "@conditional.inner",
          ["al"] = "@loop.outer",
          ["il"] = "@loop.inner",
        },
      },
    },
  }
}
